# Generated by Django 4.2.6 on 2023-10-16 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='event_image',
            new_name='blog_image',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='event_text',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
